name: 'Get Or Cache dependencies'
description: 'Retrieve or cache dependencies'
inputs:
  working_directory_path:
    description: the path of custom directory to execute npm install
    required: true
defaults:
  run:
    working-directory: ${{ inputs.working_directory_path }}
runs:
  using: 'composite'
  steps:
    - name: Cache npm packages
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      shell: bash
      run: |
        npm install
