name: 'Get Or Cache dependencies'
description: 'Retrieve or cache dependencies'
inputs:
  working-directory: # id of input
    description: 'working directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: List directory
      shell: bash
      run: |
        ls
        cd ${{ inputs.working-directory }}
        ls
    - name: Cache npm packages
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm install
