name: 'Get Or Cache dependencies'
description: 'Retrieve or cache dependencies'
inputs:
  working-directory: # id of input
    description: 'working directory'
    required: true
  cache-enabled:
    description: 'pass true or false to enable cache'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: List directory
      shell: bash
      run: |
        ls
        cd ${{ inputs.working-directory }}
        ls
    - name: Cache npm packages
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install packages
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm install
