name: Build and run tests (quiz-app\01-starting-project)

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  setup:  
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./quiz-app/01-starting-project
   steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  lint:
   needs: setup
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: ./quiz-app/01-starting-project
    steps:
      - name: Install packages
        run: |
          npm install

      - name: Linting
        run: |
          npm run lint


  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: ./quiz-app/01-starting-project

    steps:            

      - name: Build and Tests
        run: |
          npm run build

      - name: Run Tests
        run: |
          npm run test
  Deploy:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: ./quiz-app/01-starting-project

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy
        run: |
          echo "Deployed code"
          echo "${{toJSON(github)}}"
