name: Build and run tests (quiz-app\01-starting-project)

on:
  push:
    branches: ['master']
    paths:
      - 'quiz-app/01-starting-project/**'
      - 'build-quiz-app.yml'

  pull_request:
    types:
      - opened
    branches:
      - master
      - main
      - feature/*
    paths:
      - 'quiz-app/01-starting-project/**'

defaults:
  run:
    working-directory: ./quiz-app/01-starting-project

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm install

      - name: Linting
        run: |
          npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm install

      - name: Build and Tests
        run: |
          npm run build
      - name: Upload artificats
        uses: actions/upload-artficat@v4
        with:
          name: 'dist-files'
          path: |
            dist

      - name: Run Tests
        run: |
          npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          npm install

      - name: Deploy
        run: |
          echo "Deployed code"x
