name: manual workflow
on: [workflow_dispatch, issues]
jobs:
  first_job:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: 'Step 1- Print Hello'
        run: echo 'Hello world'
      - name: 'Step 2 - Print Bye'
        run: echo "Bye"
      - name: 'Multiline print'
        run: |
          echo 'first command to print'
          echo 'second command to print'
      - name: 'Print event data'
        run: |
          echo '${{toJSON(github.event)}}'
