name: manual workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 1- Print Hello'
        run: echo 'Hello world'
      - name: 'Step 2 - Print Bye'
        run: echo "Bye"
      - name: 'Multiline print'
        run: |
          echo 'first command to print'
          echo 'second command to print'
          echo '${{toJSON(github)}}'
